# Generated by Django 5.0.2 on 2024-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_priod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
